<a href="https://colab.research.google.com/github/charucheema/CMPE256_Assignment_ML_Based_Spam_Filter/blob/main/Spam_Based_Filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import string
import math
import numpy as np
import pandas as pd
import spacy
import nltk 
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer




In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

Tokenizer for english words

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
# Documents Definition
doc1 = "Free -Coupons for next movie. The above links will take you straight to our partner's site. For more information or to see other offers available, you can also visit the Groupon on the Working Advantage website."
doc2 = "Free -Coupons for next movie. The above links will take you straight to our partner's site. For more information or to see other offers available, you can also visit the Groupon on the Working Advantage website."
doc3 = "Our records indicate your Pension is under performing to see higher growth and up to 25% cash release reply PENSION for a free review. To opt out reply STOP"
doc4 = "Enter to win $25,000 and get a Free Hotel Night! Just click here for a $1 trial membership in NetMarket, the Internet'spremier discount shopping site: Fast Company EZVenture gives you FREE business articles,PLUS, you could win YOUR CHOICE of a BMW Z3 convertible, $100,000, shares of Microsoft stock, or a home office computer. Go there and get your chances to win now. A crazy-funny-cool trivia book with a $10,000 prize? PLUS chocolate, nail polish, cats, barnyard animals, and more?"
doc5 = "Dear recipient, Avangar Technologies announces the beginning of a new unprecendented global employment campaign. Due to company's exploding growth Avangar is expanding business to the European region. During last employment campaign over 1500 people worldwide took part in Avangar's business and more than half of them are currently employed by the company. And now we are offering you one more opportunity to earn extra money working with Avangar Technologies. We are looking for honest, responsible, hard-working people that can dedicate 2-4 hours of their time per day and earn extra £300-500 weekly. All offered positions are currently part-time and give you a chance to work mainly from home."
doc6 = "I know that's an incredible statement, but bear with me while I explain. You have already deleted mail from dozens of \"Get Rich Quick\" schemes, chain letter offers, and LOTS of other absurd scams that promise to make you rich overnight with no investment and no work. My offer isn't one of those. What I'm offering is a straightforward computer-based service that you can run full-or part-time like a regular business. This service runs auto-matically while you sleep, vacation, or work a \"regular\" job. It provides a valuable new service for businesses in your area. I'm offering a high-tech, low-maintenance, work-fromanywhere business that can bring in a nice comfortable additional income for your family. I did it for eight years. Since I started inviting others to join me, I've helped over 4000 do the same."
querySpam = "Free Click here visit open attachment call this number money Out extra offer available Pension Opportunity Chance Investment Pension"



In [ ]:
documents = [doc1, doc2, doc3, doc4, doc5, doc6]

In [ ]:
#Create a corpus with all input documents to be evaluated and spam query doc
'''
Please note that spam is the last document in corpus, 
this information will be instrumental when we compute the similarity between individual documents with spam query document
'''
corpus = [doc1, doc2, doc3, doc4, doc5, doc6, querySpam]

vectorizer = TfidfVectorizer(stop_words="english")                                                                                                                                                                                                   
tfidf = vectorizer.fit_transform(corpus)   
similarity_matrix = tfidf * tfidf.T    
similarity_array = similarity_matrix.toarray()    
similarity_array = similarity_matrix.toarray()    

# This similarity matrix shows similarity between all the documents in the corpus
print(similarity_array)

'''
 Lets grab the last row from the matrix to get similarity measure between
 spam query document and all other documents in the corpus.
'''

print("Lets grab the last row from the matrix to get similarity measure between spam query document and all other documents in the corpus.")
print(similarity_array[:,-1])

# We will skip the last documentt as that is the spam query document itself
for idx, val in enumerate(similarity_array[:,-1][:-1]):
    if (val > 0):
      print('Document \" %s \" contains words from spam query documentt' % (corpus[idx]))


[[1.         1.         0.02323922 0.04465679 0.03621186 0.01830851
  0.12547951]
 [1.         1.         0.02323922 0.04465679 0.03621186 0.01830851
  0.12547951]
 [0.02323922 0.02323922 1.         0.03759994 0.01781925 0.
  0.21182068]
 [0.04465679 0.04465679 0.03759994 1.         0.04096667 0.02285399
  0.04554243]
 [0.03621186 0.03621186 0.01781925 0.04096667 1.         0.08868927
  0.10791666]
 [0.01830851 0.01830851 0.         0.02285399 0.08868927 1.
  0.04364964]
 [0.12547951 0.12547951 0.21182068 0.04554243 0.10791666 0.04364964
  1.        ]]
Lets grab the last row from the matrix to get similarity measure between spam query document and all other documents in the corpus.
[0.12547951 0.12547951 0.21182068 0.04554243 0.10791666 0.04364964
 1.        ]
Document " Free -Coupons for next movie. The above links will take you straight to our partner's site. For more information or to see other offers available, you can also visit the Groupon on the Working Advantage website. " cont

In [ ]:
def compute_tf(docs_list):
    for doc in docs_list:
        doc1_lst = doc.split(" ")
        wordDict_1= dict.fromkeys(set(doc1_lst), 0)

        for token in doc1_lst:
            wordDict_1[token] +=  1
        df = pd.DataFrame([wordDict_1])
        idx = 0
        new_col = ["Term Frequency"]    
        df.insert(loc=idx, column='Document', value=new_col)

        pd.set_option('display.max_columns', None)
        print(df)
        
compute_tf([doc1, doc2, doc3,doc4,doc5,doc6])

         Document  for  or  site.  Groupon  straight  -Coupons  information  \
0  Term Frequency    1   1      1        1         1         1            1   

   above  next  other  can  movie.  you  Working  links  take  website.  our  \
0      1     1      1    1       1    2        1      1     1         1    1   

   also  the  For  Free  see  to  will  more  offers  on  visit  partner's  \
0     1    2    1     1    1   2     1     1       1   1      1          1   

   available,  The  Advantage  
0           1    1          1  
         Document  for  or  site.  Groupon  straight  -Coupons  information  \
0  Term Frequency    1   1      1        1         1         1            1   

   above  next  other  can  movie.  you  Working  links  take  website.  our  \
0      1     1      1    1       1    2        1      1     1         1    1   

   also  the  For  Free  see  to  will  more  offers  on  visit  partner's  \
0     1    2    1     1    1   2     1     1       1   1     

In [ ]:
#Normalized Term Frequency
def termFrequency(term, document):
    normalizeDocument = document.lower().split()
    return normalizeDocument.count(term.lower()) / float(len(normalizeDocument))

def compute_normalizedtf(documents):
    tf_doc = []
    for txt in documents:
        sentence = txt.split()
        norm_tf= dict.fromkeys(set(sentence), 0)
        for word in sentence:
            norm_tf[word] = termFrequency(word, txt)
        tf_doc.append(norm_tf)
        df = pd.DataFrame([norm_tf])
        idx = 0
        new_col = ["Normalized TF"]    
        df.insert(loc=idx, column='Document', value=new_col)
        pd.set_option('display.max_columns', None)
        print(df)
    return tf_doc

tf_doc = compute_normalizedtf([doc1, doc2, doc3,doc4,doc5,doc6])



        Document       for        or     site.   Groupon  straight  -Coupons  \
0  Normalized TF  0.055556  0.027778  0.027778  0.027778  0.027778  0.027778   

   information     above      next     other       can    movie.       you  \
0     0.027778  0.027778  0.027778  0.027778  0.027778  0.027778  0.055556   

    Working     links      take  website.       our      also       the  \
0  0.027778  0.027778  0.027778  0.027778  0.027778  0.027778  0.083333   

        For      Free       see        to      will      more    offers  \
0  0.055556  0.027778  0.027778  0.055556  0.027778  0.027778  0.027778   

         on     visit  partner's  available,       The  Advantage  
0  0.027778  0.027778   0.027778    0.027778  0.083333   0.027778  
        Document       for        or     site.   Groupon  straight  -Coupons  \
0  Normalized TF  0.055556  0.027778  0.027778  0.027778  0.027778  0.027778   

   information     above      next     other       can    movie.       you  \
0    

In [ ]:
def inverseDocumentFrequency(term, allDocuments):
    numDocumentsWithThisTerm = 0
    for doc in range (0, len(allDocuments)):
        if term.lower() in allDocuments[doc].lower().split():
            numDocumentsWithThisTerm = numDocumentsWithThisTerm + 1
 
    if numDocumentsWithThisTerm > 0:
        return 1.0 + math.log(float(len(allDocuments)) / numDocumentsWithThisTerm)
    else:
        return 1.0
    
def compute_idf(documents):
    idf_dict = {}
    for doc in documents:
        sentence = doc.split()
        for word in sentence:
            idf_dict[word] = inverseDocumentFrequency(word, documents)
    return idf_dict
idf_dict = compute_idf([doc1, doc2, doc3, doc4,doc5,doc6])

compute_idf([doc1, doc2, doc3,doc4,doc5,doc6])

{'"Get': 2.791759469228055,
 '"regular"': 2.791759469228055,
 '$1': 2.791759469228055,
 '$10,000': 2.791759469228055,
 '$100,000,': 2.791759469228055,
 '$25,000': 2.791759469228055,
 '-Coupons': 2.09861228866811,
 '1500': 2.791759469228055,
 '2-4': 2.791759469228055,
 '25%': 2.791759469228055,
 '4000': 2.791759469228055,
 'A': 1.4054651081081644,
 'Advantage': 2.09861228866811,
 'All': 2.791759469228055,
 'And': 1.4054651081081644,
 'Avangar': 2.791759469228055,
 "Avangar's": 2.791759469228055,
 'BMW': 2.791759469228055,
 'CHOICE': 2.791759469228055,
 'Company': 2.791759469228055,
 'Dear': 2.791759469228055,
 'Due': 2.791759469228055,
 'During': 2.791759469228055,
 'EZVenture': 2.791759469228055,
 'Enter': 2.791759469228055,
 'European': 2.791759469228055,
 'FREE': 1.4054651081081644,
 'Fast': 2.791759469228055,
 'For': 1.0,
 'Free': 1.4054651081081644,
 'Go': 2.791759469228055,
 'Groupon': 2.09861228866811,
 'Hotel': 2.791759469228055,
 'I': 2.791759469228055,
 "I'm": 2.79175946922805

In [ ]:
# tf-idf score across all docs for the query spam
def compute_tfidf_with_alldocs(documents , querySpam):
    tf_idf = []
    index = 0
    query_tokens = querySpam.split()
    query_tokens = list(set(query_tokens))
    df = pd.DataFrame(columns=['doc'] + query_tokens)
    for doc in documents:
        df['doc'] = np.arange(0 , len(documents))
        doc_num = tf_doc[index]
        sentence = doc.split()
        for word in sentence:
            for text in query_tokens:
                if(text == word):
                    idx = sentence.index(word)
                    tf_idf_score = doc_num[word] * idf_dict[word]
                    tf_idf.append(tf_idf_score)
                    df.iloc[index, df.columns.get_loc(word)] = tf_idf_score
        index += 1
    df.fillna(0 , axis=1, inplace=True)
    return tf_idf , df
            
documents = [doc1, doc2, doc3,doc4,doc5,doc6]
tf_idf , df = compute_tfidf_with_alldocs(documents , querySpam)
pd.set_option('display.max_columns', None)
print(df)


   doc    offer  Out  Click  call     extra  attachment  this  number  \
0    0  0.00000    0      0     0  0.000000           0     0       0   
1    1  0.00000    0      0     0  0.000000           0     0       0   
2    2  0.00000    0      0     0  0.000000           0     0       0   
3    3  0.00000    0      0     0  0.000000           0     0       0   
4    4  0.00000    0      0     0  0.051699           0     0       0   
5    5  0.02068    0      0     0  0.000000           0     0       0   

    Pension  Investment  Opportunity     visit  available      here  Chance  \
0  0.000000           0            0  0.058295          0  0.000000       0   
1  0.000000           0            0  0.058295          0  0.000000       0   
2  0.192535           0            0  0.000000          0  0.000000       0   
3  0.000000           0            0  0.000000          0  0.035339       0   
4  0.000000           0            0  0.000000          0  0.000000       0   
5  0.000000   

In [ ]:
documents = [d1, d2, d3, d4, d5, d6]

In [ ]:
# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
# Create the Document Term Matrix
print (stopwords.words('english'))
tfidfVectorizer = TfidfVectorizer(stop_words='english')
sparse_matrix = tfidfVectorizer.fit_transform(documents)
print(sparse_matrix.get_feature_names_out())

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

AttributeError: ignored

In [ ]:
DF = {}
for i in range(len(documents)):
    tokens = documents[i]
    for w in tokens:
        try:
            DF[w].add(i)
        except:
            DF[w] = {i}

In [ ]:
for i in DF:
  DF[i]=len(DF[i])
DF

TypeError: ignored

In [ ]:
total_vocab = [x for x in DF]
print(total_vocab)


['F', 'r', 'e', ' ', '-', 'C', 'o', 'u', 'p', 'n', 's', 'f', 'x', 't', 'm', 'v', 'i', '.', 'T', 'h', 'a', 'b', 'l', 'k', 'w', 'y', 'g', "'", ',', 'c', 'G', 'W', 'A', 'd', 'O', 'P', '2', '5', '%', 'E', 'N', 'S', 'I', '$', '0', 'H', '!', 'J', '1', 'M', ':', 'Z', 'V', 'R', 'L', 'U', 'Y', 'B', '3', 'z', '?', 'D', '4', 'Â', '£', '"', 'Q', 'j']


In [ ]:
tf_idf = {}
for i in range(N):
    tokens = documents[i]
    counter = Counter(tokens + processed_title[i])
    for token in np.unique(tokens):
        tf = counter[token]/words_count
        df = doc_freq(token)
        idf = np.log(N/(df+1))
        tf_idf[doc, token] = tf*idf

NameError: ignored

Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.

In [ ]:
doc_term_matrix = sparse_matrix.todense()
print(doc_term_matrix.shape)
df = pd.DataFrame(doc_term_matrix,
                   columns=tfidfVectorizer.get_feature_names(),
                   index=['d1', 'd2', 'd3', 'd4', 'd5', 'd6'])
print(df)

(6, 174)
         000        10       100  ...  worldwide     years        z3
d1  0.000000  0.000000  0.000000  ...   0.000000  0.000000  0.000000
d2  0.000000  0.000000  0.000000  ...   0.000000  0.000000  0.000000
d3  0.000000  0.000000  0.000000  ...   0.000000  0.000000  0.000000
d4  0.369118  0.123039  0.123039  ...   0.000000  0.000000  0.123039
d5  0.000000  0.000000  0.000000  ...   0.106858  0.000000  0.000000
d6  0.000000  0.000000  0.000000  ...   0.000000  0.109008  0.000000

[6 rows x 174 columns]


In [ ]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))

[[1.         1.         0.0268553  0.04803192 0.03379612 0.01723806]
 [1.         1.         0.0268553  0.04803192 0.03379612 0.01723806]
 [0.0268553  0.0268553  1.         0.03916376 0.01661755 0.        ]
 [0.04803192 0.04803192 0.03916376 1.         0.03912589 0.02187566]
 [0.03379612 0.03379612 0.01661755 0.03912589 1.         0.08499357]
 [0.01723806 0.01723806 0.         0.02187566 0.08499357 1.        ]]
